In [6]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [56]:
X = np.random.uniform(low=-20, high=100, size = (10000, 5))
beta = np.random.uniform(low=1, high=10, size=5)

epsilon = np.random.normal(scale=3, size=10000)
y = np.dot(X, beta) + epsilon

print(beta)

[6.32323843 3.11696186 9.51080772 1.67263503 1.79715658]


In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=91)

#scaler = StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.transform(X_test)

In [58]:
X_train = torch.from_numpy(X_train).float()
X_test = torch.from_numpy(X_test).float()

y_train = torch.from_numpy(y_train).float()

y_test = torch.from_numpy(y_test).float()

In [59]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

batch_size = 20

train = TensorDataset(X_train, y_train)

test = TensorDataset(X_test, y_test)

train_batched = DataLoader(train, batch_size, shuffle=True)

test_batched = DataLoader(test, batch_size, shuffle=True)

In [60]:
import torch.nn as nn

input_size = 5
output_size = 1

model = nn.Linear(input_size, output_size)

loss_func = nn.MSELoss(reduction='mean')

optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

In [61]:
for epoch in range(1,201):
    for x_batch, y_batch in train_batched:
        y_pred = model(x_batch)[:,0]
        loss = loss_func(y_pred, y_batch)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    if epoch%5==0:
        print('The current epoch is {}, loss is {}'.format(epoch, loss.item()))
        
        

The current epoch is 5, loss is 13.781614303588867
The current epoch is 10, loss is 9.486339569091797
The current epoch is 15, loss is 11.05943489074707
The current epoch is 20, loss is 8.779120445251465
The current epoch is 25, loss is 11.917920112609863
The current epoch is 30, loss is 11.732168197631836
The current epoch is 35, loss is 7.73874568939209
The current epoch is 40, loss is 19.633811950683594
The current epoch is 45, loss is 14.283849716186523
The current epoch is 50, loss is 11.409270286560059
The current epoch is 55, loss is 14.325010299682617
The current epoch is 60, loss is 20.812524795532227
The current epoch is 65, loss is 31.796804428100586
The current epoch is 70, loss is 9.81745433807373
The current epoch is 75, loss is 6.565893650054932
The current epoch is 80, loss is 12.615991592407227
The current epoch is 85, loss is 10.769867897033691
The current epoch is 90, loss is 12.229879379272461
The current epoch is 95, loss is 11.047857284545898
The current epoch is 

In [62]:
for name, param in model.named_parameters():
    print(name, param)


weight Parameter containing:
tensor([[6.3423, 3.0823, 9.5095, 1.6847, 1.7937]], requires_grad=True)
bias Parameter containing:
tensor([0.0276], requires_grad=True)
